### ISSUE TITLE
Stopping script while an audMixer instance is active results in freeze

### ISSUE THREAD

**Issue by StompNG** [calamity-inc/Soup-Lua-Bindings#3]
Replication .lua script and resources attached. Found while trying to brute-force ways to stop a .wav during playback. 
[script.zip](https://github.com/user-attachments/files/16301935/script.zip)

Speaking of which, _please, pretty pretty please_ expand the audio binding's functionality. Really want to make a dynamic music script, and this is my only hope. 🙏

**Comment by Sainan** [comment]
You are letting the variables go out of scope before they are finished playing, this is UB, hence your problem.
